service: eos-bpjson-api

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        - { "Fn::GetAtt": ["EosBlockProducersInfo", "Arn" ] }
  environment:
    BLOCK_PRODUCER_TABLE: { "Ref": "EosBlockProducersInfo" }

functions:
  cacheBpJson:
    handler: handler.cacheBpJson
    environment: 
      EOS_API_ENDPOINT: 'https://api.eosnewyork.io:443'
    events:
      - schedule: 
        name: daily block producer json cache
        description: Make's api calls to retrieve bp.json from block producer's and caches in dynamoDB
        rate: rate(24 hours)
        enabled: true
        input:
          key1: null
    timeout:
      - 15
  getAllProducers:
    handler: handler.getAllProducers
    environment:
      EOS_API_ENDPOINT: 'https://api.eosnewyork.io:443'
    events:
      - http:
          path: producers
          method: get
          cors: true

resources:
  Resources:
    EosBlockProducersInfo:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: producer_account_name
            AttributeType: S
        KeySchema:
          -
            AttributeName: producer_account_name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  includeDependencies:
    always:
      - 'src/lib/**' # (optional) always include these globs and their dependencies

plugins:
  - serverless-plugin-include-dependencies
